# Generated by Django 5.0.6 on 2024-06-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='duration',
            field=models.IntegerField(choices=[(0, ''), (1, 'Qisqa muddatga'), (2, 'Uzoq muddatga')], default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(choices=[(1, 'Tanlang'), (2, '1 yildan kam'), (3, '1 yildan ortiq'), (4, '3 yildan kam'), (5, '3 yildan ortiq'), (6, '5 yildan kam'), (7, '5 yildan ortiq')], default=1, max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='language',
            field=models.IntegerField(choices=[(1, 'Tanlang'), (2, "O'zbek tili"), (3, 'Ingiliz tili'), (4, 'Rus tili')], default=1, max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.IntegerField(choices=[(1, 'Tanlang'), (2, 'Dr.'), (3, 'Professor'), (4, 'Mutaxassis'), (5, 'Janob.'), (6, 'Miss'), (7, 'Xonim.')], default=1, max_length=25),
        ),
    ]
